# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12959ed0dee9f1f73010badd1f53628163cba51e840dc6924ce9b68d83e90bd6b0353dfd16501059943933e5b6d78c9536d0bb513f948bb5a708dc116cb9e0c5

test:
  secret_key_base: 1f9b711482a4ca036c77715229bf1f12aa6275e41ce2efed3fb4a99cf85a7bb83a0c0fb3579a11d88b3425d0fd7ef55df9dfda93d07c7994640ba075b75bdf0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
